import pandas as pd
convertPls = [{'name': 'Spaghetti', 'ingredients': ['pasta', 'tomato sauce', 'ground beef'], 'health_factors': ['high protein', 'low carb'], 'type': 'main', 'cook time': 20, 'cuisine': 'Italian'},
    {'name': 'Grilled Chicken', 'ingredients': ['chicken', 'oil', 'salt'], 'health_factors': ['high protein', 'low fat'], 'type': 'main', 'cook time': 15, 'cuisine': 'American'},
    {'name': 'Roasted Vegetables', 'ingredients': ['broccoli', 'carrots', 'potatoes'], 'health_factors': ['high fiber', 'low calorie'], 'type': 'side', 'cook time': 30, 'cuisine': 'Mediterranean'},
    {'name': 'Salad', 'ingredients': ['lettuce', 'tomatoes', 'cheese'], 'health_factors': ['low calorie', 'high fiber'], 'type': 'side', 'cook time': 5, 'cuisine': 'American'},
    {'name': 'Chicken Parmesan', 'ingredients': ['chicken', 'breadcrumbs', 'tomato sauce', 'mozzarella cheese'], 'health_factors': ['low-fat', 'gluten-free'], 'type': 'main', 'cook time': 45, 'cuisine': 'Italian'},
    {'name': 'Garlic Knots', 'ingredients': ['bread', 'butter', 'garlic', 'parmesan cheese'], 'health_factors': ['high-fat', 'gluten-free'], 'type': 'side', 'cook time': 60, 'cuisine': 'Italian'},
    {'name': 'Beef Stew', 'ingredients': ['beef', 'potatoes', 'carrots', 'onion', 'celery'], 'health_factors': ['high protein', 'low carb'], 'type': 'main', 'cook time': 120, 'cuisine': 'French'},
    {'name': 'Pan-Seared Salmon', 'ingredients': ['salmon', 'lemon', 'butter'], 'health_factors': ['high protein', 'low carb'], 'type': 'main', 'cook time': 20, 'cuisine': 'American'},
    {'name': 'Vegetable Stir Fry', 'ingredients': ['broccoli', 'bell pepper', 'carrots', 'soy sauce'], 'health_factors': ['high fiber', 'low fat'], 'type': 'main', 'cook time': 15, 'cuisine': 'Asian'},
    {'name': 'Quinoa Salad', 'ingredients': ['quinoa', 'cucumbers', 'tomatoes', 'feta cheese'], 'health_factors': ['high fiber', 'high protein'], 'type': 'side', 'cook time': 30, 'cuisine': 'Mediterranean'},
    {'name': 'Beef Tacos', 'ingredients': ['beef', 'taco shells', 'cheese', 'lettuce', 'tomato'], 'health_factors': ['high protein', 'low sugar'], 'type': 'main', 'cook time': 30, 'cuisine': 'Mexican'},
    {'name': 'Lemon Garlic Shrimp', 'ingredients': ['shrimp', 'lemon', 'garlic', 'butter'], 'health_factors': ['low fat', 'low carb'], 'type': 'main', 'cook time': 10, 'cuisine': 'Mediterranean'},
    {'name': 'Cauliflower Pizza', 'ingredients': ['cauliflower', 'mozzarella cheese', 'tomato sauce', 'pepperoni'], 'health_factors': ['low carb', 'gluten-free'], 'type': 'main', 'cook time': 40, 'cuisine': 'Italian'},
    {'name': 'Avocado Toast', 'ingredients': ['bread', 'avocado', 'egg'], 'health_factors': ['high fiber', 'high protein'], 'type': 'side', 'cook time': 5, 'cuisine': 'American'},
    {'name': 'Mushroom Risotto', 'ingredients': ['arborio rice', 'mushrooms', 'chicken broth', 'parmesan cheese'], 'health_factors': ['low fat', 'gluten-free'], 'type': 'main', 'cook time': 45, 'cuisine': 'Italian'},
    {'name': 'Pumpkin Soup', 'ingredients': ['pumpkin', 'chicken broth', 'cream', 'onion'], 'health_factors': ['low calorie', 'gluten-free'], 'type': 'side', 'cook time': 60, 'cuisine': 'American'},
    {'name': 'Spaghetti', 'ingredients': ['pasta', 'tomato sauce', 'ground beef'], 'health_factors': ['high protein', 'low carb'], 'type': 'main', 'cook time': 20},
    {'name': 'Grilled Chicken', 'ingredients': ['chicken', 'oil', 'salt'], 'health_factors': ['high protein', 'low fat'], 'type': 'main', 'cook time': 15},
    {'name': 'Roasted Vegetables', 'ingredients': ['broccoli', 'carrots', 'potatoes'], 'health_factors': ['high fiber', 'low calorie'], 'type': 'side', 'cook time': 30},
    {'name': 'Salad', 'ingredients': ['lettuce', 'tomatoes', 'cheese'], 'health_factors': ['low calorie', 'high fiber'], 'type': 'side', 'cook time': 5},
    {'name': 'Chicken Parmesan', 'ingredients': ['chicken', 'breadcrumbs', 'tomato sauce', 'mozzarella cheese'], 'health_factors': ['low-fat', 'gluten-free'], 'type': 'main', 'cook time': 45},
    {'name': 'Garlic Knots', 'ingredients': ['bread', 'butter', 'garlic', 'parmesan cheese'], 'health_factors': ['high-fat', 'gluten-free'], 'type': 'side', 'cook time': 60},
    {'name': 'Lentil Salad', 'ingredients': ['lentils', 'tomatoes', 'cucumber', 'feta cheese'], 'health_factors': ['high fiber', 'high protein'], 'type': 'side', 'cook time': 40, 'cuisine': 'Mediterranean'},
    {'name': 'Chicken Curry', 'ingredients': ['chicken', 'coconut milk', 'curry powder', 'rice'], 'health_factors': ['high protein', 'low sugar'], 'type': 'main', 'cook time': 60, 'cuisine': 'Indian'},
    {'name': 'Eggplant Parmesan', 'ingredients': ['eggplant', 'breadcrumbs', 'tomato sauce', 'mozzarella cheese'], 'health_factors': ['low carb', 'vegetarian'], 'type': 'main', 'cook time': 50, 'cuisine': 'Italian'},
    {'name': 'Sushi Rolls', 'ingredients': ['rice', 'nori', 'salmon', 'avocado'], 'health_factors': ['low fat', 'high protein'], 'type': 'main', 'cook time': 30, 'cuisine': 'Japanese'},
    {'name': 'Greek Salad', 'ingredients': ['lettuce', 'tomatoes', 'cucumber', 'olives', 'feta cheese'], 'health_factors': ['low calorie', 'high fiber'], 'type': 'side', 'cook time': 10, 'cuisine': 'Greek'},
    {'name': 'Baked Cod', 'ingredients': ['cod', 'lemon', 'butter', 'parsley'], 'health_factors': ['high protein', 'low fat'], 'type': 'main', 'cook time': 25, 'cuisine': 'Mediterranean'},
    {'name': 'Chili', 'ingredients': ['ground beef', 'beans', 'tomatoes', 'chili powder'], 'health_factors': ['high protein', 'high fiber'], 'type': 'main', 'cook time': 120, 'cuisine': 'American'},
    {'name': 'Ratatouille', 'ingredients': ['eggplant', 'zucchini', 'tomato', 'bell pepper'], 'health_factors': ['low calorie', 'high fiber'], 'type': 'side', 'cook time': 90, 'cuisine': 'French'},
    {'name': 'Spinach Quiche', 'ingredients': ['spinach', 'eggs', 'cream', 'cheese'], 'health_factors': ['low carb', 'vegetarian'], 'type': 'side', 'cook time': 45, 'cuisine': 'French'},
    {'name': 'Pad Thai', 'ingredients': ['rice noodles', 'shrimp', 'peanuts', 'egg', 'bean sprouts'], 'health_factors': ['high protein', 'gluten-free'], 'type': 'main', 'cook time': 30, 'cuisine': 'Thai'},
    {'name': 'Falafel Wrap', 'ingredients': ['falafel', 'lettuce', 'tomato', 'tahini sauce', 'pita bread'], 'health_factors': ['high fiber', 'vegetarian'], 'type': 'main', 'cook time': 50, 'cuisine': 'Middle Eastern'},
    {'name': 'Tom Yum Soup', 'ingredients': ['shrimp', 'lemongrass', 'mushroom', 'lime', 'chili'], 'health_factors': ['low calorie', 'gluten-free'], 'type': 'side', 'cook time': 30, 'cuisine': 'Thai'},
    {'name': 'Margherita Pizza', 'ingredients': ['dough', 'tomato sauce', 'mozzarella cheese', 'basil'], 'health_factors': ['vegetarian', 'gluten-free option'], 'type': 'main', 'cook time': 20, 'cuisine': 'Italian'},
    {'name': 'French Onion Soup', 'ingredients': ['onions', 'beef broth', 'wine', 'thyme', 'gruyere cheese'], 'health_factors': ['low calorie', 'gluten-free option'], 'type': 'side', 'cook time': 70, 'cuisine': 'French'},
    {'name': 'Tiramisu', 'ingredients': ['espresso', 'ladyfingers', 'mascarpone', 'cocoa'], 'health_factors': ['gluten-free option', 'vegetarian'], 'type': 'dessert', 'cook time': 240, 'cuisine': 'Italian'}]

df = pd.DataFrame(convertPls)
df.to_csv('testMeals.csv')