[project]
name = "Jump To Recipe"
version = "0.1.0"
description = "Creating meal plans from recipes to reduce groceries and waste"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[dependencies]
fastapi
sqlalchemy
